name: Create PR in UAT
on:
  pull_request:
    types:
      - closed
    branches:
      - DEV
      
jobs:
  Create-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Create-PR
        env: 
          GITHUB_TOKEN: ${{ secrets.GWR_GH_TOKEN }}
        run: |
          gh pr create -B UAT -H "${{github.head_ref}}" --title "${{github.head_ref}}" --body "_"
