name: Deploy to dev after approval
on:
  pull_request_review:
    types: [submitted]

jobs:
  Run-Salto-Deployment:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz
        
      - name: Create Deployment in UAT
        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
        run: |
          depl_id=$(gh pr view ${{ github.event.pull_request.number }} --json comments -q '.comments[0].body') 
          # this line grabs the deployment ID from the first comment on the PR (created by the previous workflow)
          
          ./salto-cloud deployment update from-pull-request -i $depl_id 

